# Generated by Django 4.2.4 on 2023-08-07 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_medication_medication_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usermedication',
            unique_together={('user', 'medication')},
        ),
        migrations.AlterUniqueTogether(
            name='usernutrition',
            unique_together={('user', 'nutrition')},
        ),
    ]
