# Generated by Django 4.2.4 on 2023-08-07 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_user1_connection_from_user_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='connection',
            constraint=models.UniqueConstraint(fields=('from_user', 'to_user'), name='unique_connection'),
        ),
    ]
