# Generated by Django 4.2.3 on 2023-08-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_connectionrequest'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='connectionrequest',
            constraint=models.UniqueConstraint(fields=('from_user', 'to_user'), name='unique_connection_request'),
        ),
    ]
