# Generated by Django 4.2.4 on 2023-08-09 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_connectionrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_taking_meds',
            new_name='is_taking_meds_or_supps',
        ),
    ]
