# Generated by Django 4.2.3 on 2023-08-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_connectionrequest_unique_connection_request'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='connection',
            name='unique_connection',
        ),
        migrations.RenameField(
            model_name='connection',
            old_name='from_user',
            new_name='user1',
        ),
        migrations.RenameField(
            model_name='connection',
            old_name='to_user',
            new_name='user2',
        ),
        migrations.AddConstraint(
            model_name='connection',
            constraint=models.UniqueConstraint(fields=('user1', 'user2'), name='unique_connection'),
        ),
    ]
