# Generated by Django 4.2.4 on 2023-08-09 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_is_taking_meds_user_is_taking_meds_or_supps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_taking_meds_or_supps',
            new_name='med_or_nutr_status',
        ),
    ]
