# Generated by Django 4.2.4 on 2023-08-10 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_medication_medication_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='user_input_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='직접 입력한 약 이름'),
        ),
        migrations.AddField(
            model_name='nutrition',
            name='user_input_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='직접 입력한 영양제 이름'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='medication_name',
            field=models.CharField(choices=[('blood_pressure', '혈압약'), ('diabetes', '당뇨약'), ('digestive', '소화제'), ('cholesterol', '고지혈증약'), ('constipation', '변비약'), ('digestive_system', '위장약'), ('antibiotics', '항생제'), ('antihistamines', '항히스타민제'), ('thyroid_disorder', '갑상선질환 치료제'), ('gout_treatment', '통풍 치료제'), ('anti-inflammatory', '소염 진통제'), ('antidepressants', '우울증약'), ('hormone_therapy', '성호르몬제')], max_length=100, verbose_name='복용 중인 약'),
        ),
    ]
