# Generated by Django 4.2.4 on 2023-08-10 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_connection_unique_connection_and_more'),
        ('users', '0011_alter_nutrition_nutrition_name'),
    ]

    operations = [
    ]
