# Generated by Django 4.2.4 on 2023-08-13 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_merge_20230810_2336'),
        ('users', '0012_merge_20230813_0258'),
    ]

    operations = [
    ]
