# Generated by Django 4.2.4 on 2023-08-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_merge_20230813_0432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='relationship',
        ),
        migrations.AddField(
            model_name='user',
            name='has_exercised',
            field=models.BooleanField(default=False, verbose_name='운동 여부'),
        ),
        migrations.AddField(
            model_name='user',
            name='has_medication_or_nutrition',
            field=models.BooleanField(default=False, verbose_name='약 및 영양제 섭취 여부'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_first_login',
            field=models.BooleanField(default=True, editable=False, verbose_name='첫 번째 로그인 여부'),
        ),
    ]
