# Generated by Django 4.2.4 on 2023-08-13 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_user_relationship_user_has_exercised_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medication',
            old_name='user_input_name',
            new_name='user_input_med_name',
        ),
        migrations.RenameField(
            model_name='nutrition',
            old_name='user_input_name',
            new_name='user_input_nutr_name',
        ),
    ]
