# Generated by Django 4.2.4 on 2023-08-13 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_rename_user_input_name_medication_user_input_med_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='user_input_med_name',
        ),
        migrations.RemoveField(
            model_name='nutrition',
            name='user_input_nutr_name',
        ),
        migrations.AddField(
            model_name='usermedication',
            name='user_input_med_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='직접 입력한 약 이름'),
        ),
        migrations.AddField(
            model_name='usernutrition',
            name='user_input_nutr_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='직접 입력한 영양제 이름'),
        ),
        migrations.AlterField(
            model_name='usermedication',
            name='medication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.medication', verbose_name='복용 중인 약'),
        ),
        migrations.AlterField(
            model_name='usermedication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_medications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usernutrition',
            name='nutrition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.nutrition', verbose_name='복용 중인 영양제'),
        ),
        migrations.AlterField(
            model_name='usernutrition',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_nutritions', to=settings.AUTH_USER_MODEL),
        ),
    ]
