# Generated by Django 4.2.4 on 2023-08-13 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_merge_20230813_1535'),
        ('users', '0016_remove_medication_user_input_med_name_and_more'),
    ]

    operations = [
    ]
