# Generated by Django 4.2.4 on 2023-08-14 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_merge_20230813_2301'),
        ('users', '0020_alter_user_has_exercised_and_more'),
    ]

    operations = [
    ]
