# Generated by Django 4.2.4 on 2023-08-16 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_merge_20230814_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermedication',
            name='user_input_med_name',
        ),
        migrations.RemoveField(
            model_name='usernutrition',
            name='user_input_nutr_name',
        ),
    ]
