# Generated by Django 4.2.4 on 2023-08-16 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_medication_medication_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrition',
            name='nutrition_name',
            field=models.CharField(choices=[('유산균', '유산균'), ('오메가3', '오메가3'), ('루테인', '루테인'), ('종합비타민', '종합비타민'), ('비타민C', '비타민C'), ('비타민D', '비타민D'), ('비타민A', '비타민A'), ('콜라겐', '콜라겐'), ('철분', '철분'), ('프로폴리스', '프로폴리스'), ('아로니아', '아로니아'), ('엽산', '엽산'), ('magnesium', '마그네슘'), ('비타민E', '비타민E'), ('칼슘', '칼슘')], max_length=100, unique=True, verbose_name='복용 중인 영양제'),
        ),
    ]
