# Generated by Django 4.2.2 on 2023-08-18 01:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_connectionrequest_relationship1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionrequest',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
