# Generated by Django 4.2.4 on 2023-08-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(choices=[('blood_pressure', '혈압약'), ('diabetes', '당뇨약'), ('digestive', '소화제'), ('cholesterol', '고지혈증약'), ('constipation', '변비약'), ('digestive_system', '위장약'), ('antibiotics', '항생제'), ('antihistamines', '항히스타민제'), ('thyroid_disorder', '갑상선질환 치료제'), ('gout_treatment', '통풍 치료제'), ('anti-inflammatory', '소염 진통제'), ('antidepressants', '우울증약'), ('hormone_therapy', '성호르몬제'), ('add', '직접 입력')], max_length=100, unique=True, verbose_name='복용 중인 약')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Supplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplement_name', models.CharField(choices=[('probiotics', '유산균'), ('omega3', '오메가3'), ('lutein', '루테인'), ('multivitamin', '종합비타민'), ('vitaminC', '비타민C'), ('vitaminD', '비타민D'), ('vitaminA', '비타민A'), ('collagen', '콜라겐'), ('iron', '철분'), ('propolis', '프로폴리스'), ('aronia', '아로니아'), ('folic_acid', '엽산'), ('magnesium', '마그네슘'), ('vitaminE', '비타민E'), ('calcium', '칼슘'), ('add', '직접 입력')], max_length=100, unique=True, verbose_name='복용 중인 영양제')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField(verbose_name='생일')),
                ('gender', models.CharField(choices=[('male', '남성'), ('female', '여성')], max_length=10, verbose_name='성별')),
                ('relationship', models.CharField(choices=[('father', '아빠'), ('mother', '엄마'), ('daughter', '딸'), ('son', '아들'), ('grandmother', '할머니'), ('grandfather', '할아버지'), ('grandson', '손자'), ('granddaughter', '손녀')], max_length=20, verbose_name='소중한 분과의 관계')),
                ('is_taking_meds', models.BooleanField(default=False, verbose_name='복용 중인 약 및 영양제 여부')),
                ('medication', models.ManyToManyField(blank=True, related_name='medication', to='accounts.medication')),
                ('supplement', models.ManyToManyField(blank=True, related_name='supplement', to='accounts.supplement')),
            ],
        ),
    ]
