# Generated by Django 4.2.4 on 2023-08-07 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentnutrition',
            name='nutrition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parentnutrition',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.parent'),
        ),
        migrations.AddField(
            model_name='parentmedication',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parentmedication',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.parent'),
        ),
        migrations.AddField(
            model_name='parent',
            name='children',
            field=models.ManyToManyField(related_name='parent_children', to='accounts.child'),
        ),
        migrations.AddField(
            model_name='parent',
            name='medications',
            field=models.ManyToManyField(blank=True, related_name='parents_medications', through='accounts.ParentMedication', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parent',
            name='nutritions',
            field=models.ManyToManyField(blank=True, related_name='parents_nutritions', through='accounts.ParentNutrition', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='childnutrition',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.child'),
        ),
        migrations.AddField(
            model_name='childnutrition',
            name='nutrition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='childmedication',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.child'),
        ),
        migrations.AddField(
            model_name='childmedication',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='child',
            name='medications',
            field=models.ManyToManyField(blank=True, related_name='children_medications', through='accounts.ChildMedication', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='child',
            name='nutritions',
            field=models.ManyToManyField(blank=True, related_name='children_nutritions', through='accounts.ChildNutrition', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='child',
            name='parents',
            field=models.ManyToManyField(related_name='child_parents', to='accounts.parent'),
        ),
        migrations.AddField(
            model_name='child',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
