# Generated by Django 4.2.4 on 2023-08-06 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddField(
            model_name='parent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parent',
            name='user_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='accounts.userinfo'),
        ),
        migrations.AddField(
            model_name='child',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='child',
            name='user_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='accounts.userinfo'),
        ),
    ]
