# Generated by Django 4.2.4 on 2023-08-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='child_parents', to='accounts.parent'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='parent_children', to='accounts.child'),
        ),
    ]
