# Generated by Django 4.2.4 on 2023-08-13 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_child_medications_alter_child_nutritions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childmedication',
            name='child',
        ),
        migrations.RemoveField(
            model_name='childmedication',
            name='medication',
        ),
        migrations.RemoveField(
            model_name='childnutrition',
            name='child',
        ),
        migrations.RemoveField(
            model_name='childnutrition',
            name='nutrition',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='children',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='medications',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='nutritions',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='parentmedication',
            name='medication',
        ),
        migrations.RemoveField(
            model_name='parentmedication',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='parentnutrition',
            name='nutrition',
        ),
        migrations.RemoveField(
            model_name='parentnutrition',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Child',
        ),
        migrations.DeleteModel(
            name='ChildMedication',
        ),
        migrations.DeleteModel(
            name='ChildNutrition',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
        migrations.DeleteModel(
            name='ParentMedication',
        ),
        migrations.DeleteModel(
            name='ParentNutrition',
        ),
    ]
