# Generated by Django 4.2.4 on 2023-08-15 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='accident',
            field=models.CharField(blank=True, choices=[('부딪혀서 멍이 들었어', '부딪혀서 멍이 들었어'), ('요리하다 살짝 데였어', '요리하다 살짝 데였어'), ('요리하다 살짝 베었어', '요리하다 살짝 베었어'), ('발에 걸려서 넘어졌어', '발에 걸려서 넘어졌어'), ('교통사고 났어', '교통사고 났어')], max_length=100, null=True, verbose_name='사고'),
        ),
        migrations.AlterField(
            model_name='record',
            name='eating',
            field=models.CharField(blank=True, choices=[('입맛이 없었어.. 시원한게 먹고 싶구나', '입맛이 없었어.. 시원한게 먹고 싶구나'), ('소화가 잘 안되네..', '소화가 잘 안되네..'), ('맛이 없었어..', '맛이 없었어..'), ('이가 아파서 먹기 힘들었어..', '이가 아파서 먹기 힘들었어..'), ('더부룩하고 체기가 있었어..', '더부룩하고 체기가 있었어..'), ('먹고싶은 음식이 아니었어..', '먹고싶은 음식이 아니었어..')], max_length=100, null=True, verbose_name='식사'),
        ),
        migrations.AlterField(
            model_name='record',
            name='health',
            field=models.CharField(blank=True, choices=[('무릎이 아프네..', '무릎이 아프네..'), ('비가 오려나 몸이 쑤시네..', '비가 오려나 몸이 쑤시네..'), ('머리가 아프네..', '머리가 아프네..'), ('허리가 아프네..', '허리가 아프네..'), ('가슴이 답답하네..', '가슴이 답답하네..'), ('감기기운이 있나봐..', '감기기운이 있나봐..')], max_length=100, null=True, verbose_name='건강'),
        ),
        migrations.AlterField(
            model_name='record',
            name='mood',
            field=models.CharField(blank=True, choices=[('오늘은 좀 울적하네..', '오늘은 좀 울적하네..'), ('오늘은 좀 꿀꿀해', '오늘은 좀 꿀꿀해'), ('오늘 좀 심심했어', '오늘 좀 심심했어'), ('오늘 답답한 일이 있었어..', '오늘 답답한 일이 있었어..'), ('화가나는 일이 있었어!', '화가나는 일이 있었어!'), ('짜증나는 일이 있었어!', '짜증나는 일이 있었어!')], max_length=100, null=True, verbose_name='기분'),
        ),
        migrations.AlterField(
            model_name='record',
            name='sleep',
            field=models.CharField(blank=True, choices=[('밤새 악몽을 꿨어', '밤새 악몽을 꿨어'), ('잠이 안와서 뒤척였어..', '잠이 안와서 뒤척였어..'), ('자꾸 깼어ㅠㅠ', 3), ('화장실을 자주 갔어..', '화장실을 자주 갔어..'), ('자는데 소음때문에 힘들었어', '자는데 소음때문에 힘들었어')], max_length=100, null=True, verbose_name='수면'),
        ),
    ]
