# Generated by Django 4.2.2 on 2023-08-15 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='happyorsad',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='expression',
            field=models.CharField(choices=[('best', '최고예요'), ('munan', '무난해요'), ('soso', '그럭저럭'), ('notgood', '안좋아요'), ('bad', '나빠요')], max_length=20, null=True, verbose_name='표정'),
        ),
    ]
