# Generated by Django 4.2.4 on 2023-08-15 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_alter_record_accident_alter_record_eating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='sleep',
            field=models.CharField(blank=True, choices=[('밤새 악몽을 꿨어', '밤새 악몽을 꿨어'), ('잠이 안와서 뒤척였어..', '잠이 안와서 뒤척였어..'), ('자꾸 깼어ㅠㅠ', '자꾸 깼어ㅠㅠ'), ('화장실을 자주 갔어..', '화장실을 자주 갔어..'), ('자는데 소음때문에 힘들었어', '자는데 소음때문에 힘들었어')], max_length=100, null=True, verbose_name='수면'),
        ),
    ]
