# Generated by Django 4.2.4 on 2023-08-15 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_alter_record_sleep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='expression',
            field=models.CharField(choices=[('best', '최고예요'), ('munan', '무난해요'), ('soso', '그럭저럭'), ('notgood', '안좋아요'), ('bad', '나빠요')], max_length=20, null=True, verbose_name='표정'),
        ),
    ]
