# Generated by Django 4.2.3 on 2023-08-17 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_record_happyorsad_alter_record_expression'),
        ('record', '0004_alter_record_expression'),
    ]

    operations = [
    ]
