# Generated by Django 4.2.4 on 2023-08-13 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='content',
        ),
        migrations.AddField(
            model_name='message',
            name='customContent',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='message',
            name='recommendContent',
            field=models.CharField(choices=[(1, '벚꽃이 안개한 요즘, 벚꽃 보면 어떤 생각 들어?'), (2, '요새 가장 땡기는 음식은?'), (3, '놀러가고 싶은 곳은 없어?'), (4, '더운 날씨, 무더위 조심해, 별 일 없지?'), (5, '보고 싶어')], max_length=20, null=True, verbose_name='소중한 분과의 관계'),
        ),
    ]
