# Generated by Django 4.2.4 on 2023-08-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_alter_message_customcontent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='recommendContent',
            field=models.CharField(blank=True, choices=[('벚꽃이 안개한 요즘, 벚꽃 보면 어떤 생각 들어?', '벚꽃이 안개한 요즘, 벚꽃 보면 어떤 생각 들어?'), ('요새 가장 땡기는 음식은?', '요새 가장 땡기는 음식은?'), ('놀러가고 싶은 곳은 없어?', '놀러가고 싶은 곳은 없어?'), ('더운 날씨, 무더위 조심해, 별 일 없지?', '더운 날씨, 무더위 조심해, 별 일 없지?'), ('보고 싶어', '보고 싶어')], max_length=100, null=True, verbose_name='추천하는 메시지'),
        ),
    ]
